#!/usr/bin/env bash

APP="podcatcher"

BUILD_HOST="localhost"
BUILD_USER="danjac"
BUILD_AT="/tmp/edeliver/podcatcher/builds"

STAGING_HOSTS="podbaby.me"
STAGING_USER="deploy"
DELIVER_TO="/home/deploy/apps"

# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/builder/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
      cd assets && npm install && ./node_modules/brunch/bin/brunch b -p
      cd .. && MIX_ENV=prod mix phx.digest
    "
  fi
}
